### ISSUE TITLE
Dependency: markdown-checklist

### ISSUE THREAD

**Issue by piyueh** [fboender/mdpreview#2]
Hi, thanks for this nice app. When I tried to use it, I also had to install [markdown-checklist](https://github.com/FND/markdown-checklist) to make it work. But this package is not listed as a dependency in README. So is this a dependency? I just want to make sure. Thanks!

**Comment by fboender** [comment]
Apparently it is. Totally missed that in the README. The dependency is present in the `requirements.txt` file, which is how I usually installed dependencies. I'll clarify the README a bit.

Thanks for mentioning it!
