### ISSUE TITLE
block-quotes don't seem to work

### ISSUE THREAD

**Issue by telamon** [fboender/mdpreview#4]
Hi!
First of all, thanks for this piece of software it's just what i needed.
But for some reason block-quotes / tripple-backticks don't get rendered properly 

Not sure what's wrong but:
![image](https://user-images.githubusercontent.com/148454/176717712-690f561a-5bda-44de-9f47-7863ebb3e317.png)

gets rendered as:
![image](https://user-images.githubusercontent.com/148454/176717604-76991d3e-6152-493b-be35-d2a78ba19e7c.png)

But should look like:
# Example

`1 2 3`

```
4
5
6
```

Thanks!

**Comment by fboender** [comment]
Apparently this is not a standard Markdown feature? I had no idea. I enabled support for [fenced code blocks](https://python-markdown.github.io/extensions/fenced_code_blocks/) in the latest commit. It's working for me now.

**Comment by telamon** [comment]
Thank you! =)
